---
app:
  persistence:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      username: app
      password: sqlpass
      url: jdbc:mariadb://localhost:3307/umasio?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    
    jpa:
      dialect: org.hibernate.dialect.MariaDB53Dialect
      generate-ddl: false
      show-sql: false
      properties:
        hibernate.temp.use_jdbc_metadata_defaults: false
  domain: ldpld1.um.es
 # CORS
  cors:
    enabled: true
    allowedOrigin: '*'
    allowedMethods: GET,POST,PUT,DELETE
    allowedHeaders:
      - Authorization
      - X-Requested-With
      - Content-Type
    maxAge: 3600
  shape-validator:
    enabled: true
    endpoint: http://localhost:8090/api
  kafka:
    discovery-action-topic-name: discovery_action
    general-contingency-topic-name: general-contingency-data
    general-topic-name: general-data
    general-link-topic-name: general-link-data
    management-topic-name: management-data
    import-error-topic-name: import-error
    create-topics: false
  generator-uris:
    mockup:
      enabled: false
    endpoint: http://localhost:9326
    endpoint-root-uri: ${app.generator-uris.endpoint}/uri-factory/root/uri
    endpoint-resource-id: ${app.generator-uris.endpoint}/uri-factory/canonical/resource
    endpoint-property: ${app.generator-uris.endpoint}/uri-factory/canonical/property
    endpoint-resource-type: ${app.generator-uris.endpoint}/uri-factory/canonical/entity
    endpoint-local: ${app.generator-uris.endpoint}/uri-factory/local

# Cache configuration
  cache:
    embedded:
      enabled: true

  # Swagger
  swagger:
    enabled: false
  #ActiveMQ
  activemq:
    queue-name: management-data 
   
# Spring configuration
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers:
        - localhost:9092
      group-id: management-system
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
    broker:
      jmx:
        createConnector: false  

## Actuator
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /management
  server:
    port: 9321

## In case of configure web endpoints, remove it or change port number
server:
  port: ${management.server.port}

### log
logging:
  level:
    es.um.asio.service: INFO