---
app:
  kafka:
    general-topic-name: general-data
    management-topic-name: management-data
    create-topics: false
  generator-uris:
    mockup:
      enabled: false
    endpoint: http://localhost:9326
    endpoint-root-uri: ${app.generator-uris.endpoint}/uri-factory/root/uri
    endpoint-resource-id: ${app.generator-uris.endpoint}/uri-factory/canonical/resource
    endpoint-property: ${app.generator-uris.endpoint}/uri-factory/canonical/property
    endpoint-resource-type: ${app.generator-uris.endpoint}/uri-factory/canonical/entity
   
# Spring configuration
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers:
        - localhost:29092
      group-id: management-system
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      ## Actuator
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /management
  server:
    port: 9321

## In case of configure web endpoints, remove it or change port number
server:
  port: ${management.server.port}